export enum ExecutionState {
  IDLE = "IDLE",

  VALIDATING = "VALIDATING",

  CAPITAL_ALLOCATED = "CAPITAL_ALLOCATED",

  RISK_APPROVED = "RISK_APPROVED",

  BUY_ORDER_SENT = "BUY_ORDER_SENT",

  BUY_FILLED = "BUY_FILLED",

  SELL_ORDER_SENT = "SELL_ORDER_SENT",

  SELL_FILLED = "SELL_FILLED",

  COMPLETED = "COMPLETED",

  BUY_FAILED = "BUY_FAILED",

  SELL_FAILED = "SELL_FAILED",

  CANCELLED = "CANCELLED",

  TIMEOUT = "TIMEOUT",

  ROLLBACK = "ROLLBACK",
}